### ISSUE TITLE
[Q] Regarding: "How to play with apktool on android"

### ISSUE THREAD

**Issue by Lanchon** [dongfangxunlei/openjdk#2]
Regarding: https://github.com/dongfangxunlei/openjdk/wiki/How-to-play-with-apktool-on-android

apktool.jar includes native builds of AAPT and AAPT2 (for linux windows and osx, 32 and 64 bit) in the nested `/prebuilt` folder. there are no ARM builds.

without testing, it looks like apktool would be able to decode an app but not to rebuild it. can you comment on this? thanks!

**Comment by pangqingyuan1991** [comment]
You need to download apktool.jar from the app.

**Comment by Lanchon** [comment]
thanks!

ok, i see that by "download apktool.jar" he meant his own fork of apktool.

for reference, here are the android binaries:
https://github.com/dongfangxunlei/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt
