### ISSUE TITLE
[Q] arm64 vs aarch64

### ISSUE THREAD

**Issue by Lanchon** [dongfangxunlei/openjdk#3]
the releases section has builds for arm64 and aarch64 archs. AFAIK, they are the same arch. what are there two builds? thanks!

**Comment by pangqingyuan1991** [comment]
arm64 is developed by Oracle, and aarch64 is by community. You can choose any one you like.

**Comment by Lanchon** [comment]
thanks for your answer, but it is not clear.

arm64 and aarch64 are archs. AFAIK, oracle does not develop native compilers such as LLVM or GCC, so they don't develop archs.

horrible company Apple developed an LLVM fork for aarch64 which they called arm64 (though ARM calls their arch aarch64). they open sourced it, but being horrible, they only did it after the community had developed their own port for aarch64, called aarch64. the arm64 and aarch64 ports of LLVM were merged by the community, and the result called aarch64. now there is one single arch in LLVM, and it is called aarch64. GCC also has an aarch64 arch, also called aarch64.

AFAIK, there is no arch called arm64 anymore. so my question remains.

**Comment by pangqingyuan1991** [comment]
@Lanchon See https://openjdk.java.net/jeps/340

**Comment by Lanchon** [comment]
thanks! ok so there are 2 aarch64 hotspot ports. and they want to ge rid of the one called arm64, so i guess we should focus on aarch64. thanks!
