### ISSUE TITLE
With Terminal?

### ISSUE THREAD

**Issue by HemanthJabalpuri** [dongfangxunlei/openjdk#4]
@dongfangxunlei

Is it possible to use openjdk in Terminal Emulator  or Termux apps?

If not atleast from app like we can use Busybox from Busybox app by meefik without root access?

Thanks

**Comment by dongfangxunlei** [comment]
Yeah, it is possible. But command line need some extra options to run java command. It is not very handy to use with Terminal.

**Comment by HemanthJabalpuri** [comment]
@dongfangxunlei

[Igneous - IDE for Java (Early Access)](https://www.google.co.in/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.sparseway.igneous%26hl%3Den_IN%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Digneous%2B-%2Bide%2Bfor%2Bjava%26pcampaignid%3DAPPU_1_k3VLXefZMd2mwgORhIWIAg&ved=2ahUKEwin79rWivLjAhVdk3AKHRFCASEQ5YQBMAB6BAgKEAI&usg=AOvVaw2-pZ7L2g4oxttxjaYp-hwe) uses openjdk for compiling java....

Is it possible to get some reference from that app and making command line compatible?

**Comment by dongfangxunlei** [comment]
@HemanthJabalpuri 
Looks crazy to develop full java app with phone.

**Comment by HemanthJabalpuri** [comment]
@dongfangxunlei

I have some small questions about apktool.

-If there are prebuilt binaries of aapt in apktool then when we have to use external ones?

-If we are using apktool to decompile other than system apps like Twitter app, then should we have to install framework before decompiling?

-if we are decompiling a different mobile's apk in our mobile, then which framework should be installed? other mobiles's or our's?

**Comment by dongfangxunlei** [comment]
armv7?? What is the age of your device?

**Comment by HemanthJabalpuri** [comment]
@dongfangxunlei
I have a 2015 year made mobile running on 6.0.

Can you please answer above post questions...please
