### ISSUE TITLE
App crashes after pressing Decompile button in the popup window.

### ISSUE THREAD

**Issue by parind** [dongfangxunlei/openjdk#5]
I am running Android 6 arm64 w/o root, using OpenJDK_arm64 and the latest apktool_2.4.1_SNAPSHOT. 
Everything works fine, until I browse to an apk after importing framework, and choose decompile, 
followed by which I am allowed to select the apktool version I need and the other options like
 "no resources", "no sources", etc, and then pressing "Decompile" crashes the app. 

Any opinions.

[log.txt](https://github.com/dongfangxunlei/openjdk/files/3677293/log.txt)

**Comment by dongfangxunlei** [comment]
Well, take it easy

**Comment by parind** [comment]
Uh, well what should I do? Is the error on my end, or app needs a fix ? 

DongFangXunlei, does it work without root. I think I read it somewhere in the repo HOW-TO's.

**Comment by dongfangxunlei** [comment]
Yeah, there is something wrong with the merge from upstream. I have fixed it. Please download https://github.com/dongfangxunlei/AmazeFileManager/releases/download/continuous/amaze.apk again

**Comment by parind** [comment]
Annd..  Its Working !! Thanks for the fix.

**Comment by parind** [comment]
Now its running, I am closing this thread. If any other issues will create a new thread.
